name: first work flow

on:
  - workflow_dispatch

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some Text
        run: echo "some text"
      - name: Display Some New text
        run: echo "some new text"
      - name: Some Long command
        run: |
          node -v
          npm -v
  run-second-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some Text Parallel
        run: echo "text paralel"
  run-waiting-command:
    runs-on: ubuntu-latest
    steps:
      - name: Wait For Two Jobs To End
        run: echo "joined"