name: first work flow

on:
  - push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some Text
        run: echo "some text"
      - name: Display Some New text
        run: echo "some new text"
      - name: Some Long command
        run: |
          node -v
          npm -v
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      #- uses: actions/checkout@v4
      - name: Display Repo Content
        run: |
          pwd
          ls -a
  run-second-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display Some Text Parallel
        run: echo "text paralel"
  run-waiting-command:
    runs-on: ubuntu-latest
    steps:
      - name: Wait For Two Jobs To End
        run: echo "joined"
